<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    
public function findOrderedAndFiltered($over_id=0, $over_rating=-1, $start_title='', $order_by='title DESC'){
    
$em = $this->getEntityManager();
$movies = $em->createQuery(
'SELECT	m FROM AppBundle:Movie
WHERE 1=1
AND m.id > movie_id
AND m.rating > :movie:rating
AND m.title LIKE LOWER(:movie_title)
ORDER BY m.' . $order_by
        )
->setParameter("movie_id", $over_id)
->setParameter("movie_rating", $over_rating)
->setParameter("movie_title", $start_title . '%')        
->getResult();
	
return	$movies;
}
}
